[build]
  base    = "/"
  publish = "public"
  command = "hugo"

[build.environment]
  HUGO_VERSION = "0.112.5"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

  [functions.send-email]
    schedule = "23 12 18 * *"