[build]
  base    = "/"
  publish = "public"
  command = "hugo"

[build.environment]
  HUGO_VERSION = "0.157.0"
  NODE_VERSION = "20.19.3"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
